language: generic

os: osx
osx_image: xcode9.4

before_install:
  - curl -LO https://raw.githubusercontent.com/aferrero2707/macports-ci/master/macports-ci
  - brew remove --force --ignore-dependencies libtiff libpng jpeg openjpeg
  - source ./macports-ci install
  #- sudo mv /usr/local /usr/_local
  #- brew update && brew install ccache
  #- export PATH="/usr/local/opt/ccache/libexec:$PATH"
  #- brew update
  #- brew cask uninstall oclint || true
  #- brew install ffmpeg curl expat libffi fftw glib zlib openexr cmake #opencv@2 
  #- git clone https://github.com/aferrero2707/homebrew-bottles.git
  #- bash homebrew-bottles/install-bottles.sh
  #- brew install curl expat glib
  #- brew upgrade cmake
  - sudo /opt/local/bin/port install cmake openexr opencv tiff openjpeg libpng libjpeg
  - bash ./build-osx.sh
  #- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash ./build-osx.sh; fi
  - ls
  - wget -c https://github.com/aferrero2707/uploadtool/raw/master/upload_rotate.sh
  - bash  ./upload_rotate.sh "continuous" *.tgz >& /dev/null

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)$/
    - /^(?i:unstable)$/
